export type Language = 'ka' | 'en' | 'ru' | 'tr'
export type Theme = 'light' | 'dark'

export const localeMap: Record<Language, string> = { ka: 'ka-GE', en: 'en', ru: 'ru', tr: 'tr' }

type TranslationMap = Record<string, string>

const ka: TranslationMap = {
  'nav.home': 'მთავარი', 'nav.transactions': 'ტრანზაქციები', 'nav.shopping': 'საყიდლების სია', 'nav.budget': 'ბიუჯეტი', 'nav.accounts': 'ანგარიშები', 'nav.family': 'ოჯახი', 'nav.debts': 'ვალები და განვადებები', 'nav.savings': 'დანაზოგები', 'nav.statistics': 'სტატისტიკა', 'nav.settings': 'პარამეტრები', 'nav.more': 'მეტი',
  'common.search': 'ძებნა', 'common.addIncome': '+ შემოსავლის დამატება', 'common.addExpense': '+ ხარჯის დამატება', 'common.save': 'შენახვა', 'common.cancel': 'გაუქმება', 'common.edit': 'რედაქტირება', 'common.delete': 'წაშლა', 'common.close': 'დახურვა', 'common.notifications': 'შეტყობინებები',
  'header.enableDark': 'ღამის რეჟიმი', 'header.enableLight': 'დღის რეჟიმი', 'header.language': 'ენის არჩევა', 'header.currency': 'ვალუტის არჩევა',
  'notifications.title': 'შეტყობინებები', 'notifications.markAll': 'ყველას წაკითხულად მონიშვნა', 'notifications.empty': 'ფინანსური შეტყობინებები არ არის', 'notifications.markRead': 'წაკითხულად მონიშვნა', 'notifications.debtDue': '{name} — {amount}-ის გადახდის ვადა: {date}', 'notifications.debtOverdue': '{name} — გადახდის ვადა გასულია ({date})', 'notifications.budgetWarning': '{category}: გამოყენებულია {spent} / {limit}', 'notifications.budgetExceeded': '{category}: ბიუჯეტის ლიმიტი გადაჭარბებულია ({spent} / {limit})', 'notifications.savingsAchieved': 'მიზანი „{name}“ მიღწეულია', 'notifications.reminder': 'შეხსენება: „{name}“ — {date}',
  'transaction.amount': 'თანხა', 'transaction.expenseType': 'ხარჯის ტიპი', 'transaction.personal': 'პირადი', 'transaction.shared': 'ოჯახის საერთო', 'transaction.category': 'კატეგორია', 'transaction.description': 'აღწერა', 'transaction.incomePlaceholder': 'მაგ: ხელფასი, ბონუსი ან სხვა', 'transaction.expensePlaceholder': 'მაგ: სუპერმარკეტი, საწვავი ან სხვა', 'transaction.date': 'თარიღი', 'transaction.account': 'ანგარიში', 'transaction.familyMember': 'ოჯახის წევრი', 'transaction.error.amount': 'შეიყვანეთ სწორად თანხა', 'transaction.error.description': 'აღწერა სავალდებულოა', 'transaction.error.people': 'აირჩიეთ ანგარიში და ოჯახის წევრი',
  'receipt.label': 'ჩეკის ფოტო', 'receipt.optional': 'არასავალდებულო', 'receipt.add': '📷 ჩეკის ფოტოს დამატება', 'receipt.processing': 'ფოტო მუშავდება…', 'receipt.replace': 'ფოტოს შეცვლა', 'receipt.remove': 'ფოტოს წაშლა', 'receipt.view': 'ჩეკის ნახვა', 'receipt.attached': '📎 ჩეკი', 'receipt.previewAlt': 'ჩეკის ფოტოს გადახედვა', 'receipt.help': 'ფოტო შეიკუმშება და უსაფრთხოდ შეინახება ამ მოწყობილობაზე.', 'receipt.error.notImage': 'გთხოვთ აირჩიოთ გამოსახულების ფაილი.', 'receipt.error.tooLarge': 'ფოტო ძალიან დიდია. აირჩიეთ 12 მბ-ზე ნაკლები ფაილი.', 'receipt.error.processingFailed': 'ფოტოს დამუშავება ვერ მოხერხდა. სცადეთ JPG ან PNG ფაილი.',
  'receipt.ocrProcessing': 'ჩეკი მუშავდება…', 'receipt.ocrDetected': 'თანხა ავტომატურად ამოიცნო', 'receipt.ocrUncertain': 'თანხა ზუსტად ვერ ამოვიცანით — გადაამოწმეთ', 'receipt.detectedBadge': '✓ ჩეკიდან ამოცნობილი', 'receipt.viewerControls': 'ჩეკის გამოსახულების კონტროლები', 'receipt.zoomIn': 'გადიდება', 'receipt.zoomOut': 'დაპატარავება', 'receipt.resetZoom': 'მასშტაბის აღდგენა', 'receipt.rotateLeft': 'მარცხნივ შებრუნება', 'receipt.rotateRight': 'მარჯვნივ შებრუნება',
  'receipt.ocrReading': 'ჩეკიდან თანხის ამოკითხვა…', 'receipt.ocrFailed': 'ჩეკიდან თანხა ვერ ამოვიცანი — ჩაწერეთ ხელით', 'receipt.reprocess': 'თანხის თავიდან ამოკითხვა',
  'attachments.label': 'ფაილები და დოკუმენტები', 'attachments.add': '+ ფაილების დამატება', 'attachments.help': 'შეგიძლიათ დაამატოთ ფოტო, PDF, Excel ან Word დოკუმენტი', 'attachments.view': 'ნახვა', 'attachments.viewPdf': 'PDF-ის ნახვა', 'attachments.open': 'გახსნა/ჩამოტვირთვა', 'attachments.replace': 'შეცვლა', 'attachments.remove': 'წაშლა', 'attachments.readAmount': 'ჩეკიდან თანხის ამოკითხვა', 'attachments.title': 'მიმაგრებული ფაილები', 'attachments.viewAll': 'ფაილების ნახვა', 'attachments.file': 'ფაილი', 'attachments.files': 'ფაილი', 'attachments.saving': 'ინახება…', 'attachments.error.unsupported': 'ამ ტიპის ფაილი არ არის მხარდაჭერილი.', 'attachments.error.tooLarge': 'ფაილი ძალიან დიდია. მაქსიმალური ზომაა 15 მბ.', 'attachments.error.duplicate': 'ეს ფაილი უკვე დამატებულია.', 'attachments.error.open': 'ფაილის გახსნა ვერ მოხერხდა.', 'attachments.error.save': 'ფაილების შენახვა ვერ მოხერხდა. შეამოწმეთ ბრაუზერის საცავი და სცადეთ თავიდან.',
  'settings.eyebrow': 'პარამეტრები', 'settings.title': 'აპლიკაციის პარამეტრები', 'settings.appearance': 'გარეგნობა', 'settings.appearanceDescription': 'აირჩიეთ აპლიკაციის სასურველი რეჟიმი', 'settings.light': '☀️ დღის რეჟიმი', 'settings.dark': '🌙 ღამის რეჟიმი', 'settings.language': 'ენა', 'settings.languageDescription': 'აირჩიეთ აპლიკაციის ენა', 'settings.localData': 'ადგილობრივი მონაცემები', 'settings.localDataDescription': 'თქვენი ფინანსები ინახება ამ ბრაუზერში და დარჩება გვერდის განახლების შემდეგ.', 'settings.reset': 'დემო მონაცემების აღდგენა', 'settings.resetConfirm': 'ყველა ადგილობრივი მონაცემი წაიშლება. გაგრძელება?',
  'shopping.title': 'საყიდლების სია', 'shopping.eyebrow': 'ოჯახის საერთო სია', 'shopping.add': '+ პროდუქტის დამატება', 'shopping.product': 'პროდუქტის დასახელება', 'shopping.quantity': 'რაოდენობა', 'shopping.category': 'კატეგორია', 'shopping.price': 'ერთეულის სავარაუდო ფასი', 'shopping.addedBy': 'ვინ დაამატა', 'shopping.note': 'შენიშვნა', 'shopping.pending': 'საყიდელი', 'shopping.purchased': 'შეძენილია', 'shopping.markPurchased': 'შეძენილად მონიშვნა', 'shopping.undo': 'შეძენის გაუქმება', 'shopping.purchasedBy': 'შეიძინა',
  'transactions.eyebrow': 'ტრანზაქციები', 'transactions.title': 'ყველა მოძრაობა', 'dashboard.welcome': 'მოგესალმებით 👋', 'dashboard.recent': 'ბოლო ტრანზაქციები', 'dashboard.seeAll': 'ყველას ნახვა', 'dashboard.budget': 'მთვიური ბიუჯეტი', 'dashboard.quickActions': 'სწრაფი ქმედებები',
}

const en: TranslationMap = {
  'nav.home': 'Home', 'nav.transactions': 'Transactions', 'nav.shopping': 'Shopping List', 'nav.budget': 'Budget', 'nav.accounts': 'Accounts', 'nav.family': 'Family', 'nav.debts': 'Debts & Installments', 'nav.savings': 'Savings', 'nav.statistics': 'Statistics', 'nav.settings': 'Settings', 'nav.more': 'More',
  'common.search': 'Search', 'common.addIncome': '+ Add income', 'common.addExpense': '+ Add expense', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.edit': 'Edit', 'common.delete': 'Delete', 'common.close': 'Close', 'common.notifications': 'Notifications',
  'header.enableDark': 'Switch to dark mode', 'header.enableLight': 'Switch to light mode', 'header.language': 'Choose language', 'header.currency': 'Choose currency',
  'notifications.title': 'Notifications', 'notifications.markAll': 'Mark all as read', 'notifications.empty': 'No financial notifications', 'notifications.markRead': 'Mark as read', 'notifications.debtDue': '{name} — {amount} payment due {date}', 'notifications.debtOverdue': '{name} — payment overdue ({date})', 'notifications.budgetWarning': '{category}: {spent} of {limit} used', 'notifications.budgetExceeded': '{category}: budget limit exceeded ({spent} / {limit})', 'notifications.savingsAchieved': '“{name}” savings goal achieved', 'notifications.reminder': 'Reminder: “{name}” — {date}',
  'transaction.amount': 'Amount', 'transaction.expenseType': 'Expense type', 'transaction.personal': 'Personal', 'transaction.shared': 'Shared family', 'transaction.category': 'Category', 'transaction.description': 'Description', 'transaction.incomePlaceholder': 'e.g. Salary, bonus, or other', 'transaction.expensePlaceholder': 'e.g. Groceries, fuel, or other', 'transaction.date': 'Date', 'transaction.account': 'Account', 'transaction.familyMember': 'Family member', 'transaction.error.amount': 'Enter a valid amount', 'transaction.error.description': 'Description is required', 'transaction.error.people': 'Select an account and family member',
  'receipt.label': 'Receipt photo', 'receipt.optional': 'optional', 'receipt.add': '📷 Add receipt photo', 'receipt.processing': 'Processing photo…', 'receipt.replace': 'Change photo', 'receipt.remove': 'Remove photo', 'receipt.view': 'View receipt', 'receipt.attached': '📎 Receipt', 'receipt.previewAlt': 'Receipt photo preview', 'receipt.help': 'The photo will be compressed and stored safely on this device.', 'receipt.error.notImage': 'Please select an image file.', 'receipt.error.tooLarge': 'This photo is too large. Choose a file under 12 MB.', 'receipt.error.processingFailed': 'The photo could not be processed. Try a JPG or PNG file.',
  'receipt.ocrProcessing': 'Processing receipt…', 'receipt.ocrDetected': 'Amount detected automatically', 'receipt.ocrUncertain': 'We could not detect the amount reliably — please check it', 'receipt.detectedBadge': '✓ Detected from receipt', 'receipt.viewerControls': 'Receipt image controls', 'receipt.zoomIn': 'Zoom in', 'receipt.zoomOut': 'Zoom out', 'receipt.resetZoom': 'Reset zoom', 'receipt.rotateLeft': 'Rotate left', 'receipt.rotateRight': 'Rotate right',
  'receipt.ocrReading': 'Reading amount from receipt…', 'receipt.ocrFailed': 'Could not detect an amount from the receipt — enter it manually', 'receipt.reprocess': 'Read amount again',
  'attachments.label': 'Files and documents', 'attachments.add': '+ Add files', 'attachments.help': 'You can add a photo, PDF, Excel, or Word document', 'attachments.view': 'View', 'attachments.viewPdf': 'View PDF', 'attachments.open': 'Open/download', 'attachments.replace': 'Replace', 'attachments.remove': 'Remove', 'attachments.readAmount': 'Read amount from receipt', 'attachments.title': 'Attached files', 'attachments.viewAll': 'View files', 'attachments.file': 'file', 'attachments.files': 'files', 'attachments.saving': 'Saving…', 'attachments.error.unsupported': 'This file type is not supported.', 'attachments.error.tooLarge': 'This file is too large. The maximum size is 15 MB.', 'attachments.error.duplicate': 'This file has already been added.', 'attachments.error.open': 'The file could not be opened.', 'attachments.error.save': 'The files could not be saved. Check browser storage and try again.',
  'settings.eyebrow': 'Settings', 'settings.title': 'Application settings', 'settings.appearance': 'Appearance', 'settings.appearanceDescription': 'Choose your preferred application mode', 'settings.light': '☀️ Light mode', 'settings.dark': '🌙 Dark mode', 'settings.language': 'Language', 'settings.languageDescription': 'Choose your application language', 'settings.localData': 'Local data', 'settings.localDataDescription': 'Your finances are stored in this browser and remain after refreshing the page.', 'settings.reset': 'Reset demo data', 'settings.resetConfirm': 'All local data will be deleted. Continue?',
  'shopping.title': 'Shopping List', 'shopping.eyebrow': 'Shared household list', 'shopping.add': '+ Add product', 'shopping.product': 'Product name', 'shopping.quantity': 'Quantity', 'shopping.category': 'Category', 'shopping.price': 'Estimated unit price', 'shopping.addedBy': 'Added by', 'shopping.note': 'Note', 'shopping.pending': 'To buy', 'shopping.purchased': 'Purchased', 'shopping.markPurchased': 'Mark as purchased', 'shopping.undo': 'Undo purchase', 'shopping.purchasedBy': 'Purchased by',
  'transactions.eyebrow': 'Transactions', 'transactions.title': 'All activity', 'dashboard.welcome': 'Welcome 👋', 'dashboard.recent': 'Recent transactions', 'dashboard.seeAll': 'See all', 'dashboard.budget': 'Monthly budget', 'dashboard.quickActions': 'Quick actions',
}

const ru: TranslationMap = {
  'nav.home': 'Главная', 'nav.transactions': 'Транзакции', 'nav.shopping': 'Список покупок', 'nav.budget': 'Бюджет', 'nav.accounts': 'Счета', 'nav.family': 'Семья', 'nav.debts': 'Долги и рассрочки', 'nav.savings': 'Сбережения', 'nav.statistics': 'Статистика', 'nav.settings': 'Настройки', 'nav.more': 'Ещё',
  'common.search': 'Поиск', 'common.addIncome': '+ Добавить доход', 'common.addExpense': '+ Добавить расход', 'common.save': 'Сохранить', 'common.cancel': 'Отмена', 'common.edit': 'Изменить', 'common.delete': 'Удалить', 'common.close': 'Закрыть', 'common.notifications': 'Уведомления',
  'header.enableDark': 'Включить тёмный режим', 'header.enableLight': 'Включить светлый режим', 'header.language': 'Выбрать язык', 'header.currency': 'Выбрать валюту',
  'notifications.title': 'Уведомления', 'notifications.markAll': 'Отметить все прочитанными', 'notifications.empty': 'Финансовых уведомлений нет', 'notifications.markRead': 'Отметить прочитанным', 'notifications.debtDue': '{name} — платёж {amount} до {date}', 'notifications.debtOverdue': '{name} — платёж просрочен ({date})', 'notifications.budgetWarning': '{category}: использовано {spent} из {limit}', 'notifications.budgetExceeded': '{category}: лимит бюджета превышен ({spent} / {limit})', 'notifications.savingsAchieved': 'Цель «{name}» достигнута', 'notifications.reminder': 'Напоминание: «{name}» — {date}',
  'transaction.amount': 'Сумма', 'transaction.expenseType': 'Тип расхода', 'transaction.personal': 'Личный', 'transaction.shared': 'Общий семейный', 'transaction.category': 'Категория', 'transaction.description': 'Описание', 'transaction.incomePlaceholder': 'Например: зарплата, бонус или другое', 'transaction.expensePlaceholder': 'Например: продукты, топливо или другое', 'transaction.date': 'Дата', 'transaction.account': 'Счёт', 'transaction.familyMember': 'Член семьи', 'transaction.error.amount': 'Введите корректную сумму', 'transaction.error.description': 'Описание обязательно', 'transaction.error.people': 'Выберите счёт и члена семьи',
  'receipt.label': 'Фото чека', 'receipt.optional': 'необязательно', 'receipt.add': '📷 Добавить фото чека', 'receipt.processing': 'Обработка фото…', 'receipt.replace': 'Заменить фото', 'receipt.remove': 'Удалить фото', 'receipt.view': 'Посмотреть чек', 'receipt.attached': '📎 Чек', 'receipt.previewAlt': 'Предпросмотр фото чека', 'receipt.help': 'Фото будет сжато и сохранено на этом устройстве.', 'receipt.error.notImage': 'Выберите файл изображения.', 'receipt.error.tooLarge': 'Фото слишком большое. Выберите файл меньше 12 МБ.', 'receipt.error.processingFailed': 'Не удалось обработать фото. Попробуйте файл JPG или PNG.',
  'receipt.ocrProcessing': 'Чек обрабатывается…', 'receipt.ocrDetected': 'Сумма распознана автоматически', 'receipt.ocrUncertain': 'Не удалось точно распознать сумму — проверьте её', 'receipt.detectedBadge': '✓ Распознано с чека', 'receipt.viewerControls': 'Управление изображением чека', 'receipt.zoomIn': 'Увеличить', 'receipt.zoomOut': 'Уменьшить', 'receipt.resetZoom': 'Сбросить масштаб', 'receipt.rotateLeft': 'Повернуть влево', 'receipt.rotateRight': 'Повернуть вправо',
  'receipt.ocrReading': 'Считываем сумму с чека…', 'receipt.ocrFailed': 'Не удалось распознать сумму с чека — введите её вручную', 'receipt.reprocess': 'Считать сумму ещё раз',
  'attachments.label': 'Файлы и документы', 'attachments.add': '+ Добавить файлы', 'attachments.help': 'Можно добавить фото, PDF, документ Excel или Word', 'attachments.view': 'Просмотр', 'attachments.viewPdf': 'Посмотреть PDF', 'attachments.open': 'Открыть/скачать', 'attachments.replace': 'Заменить', 'attachments.remove': 'Удалить', 'attachments.readAmount': 'Считать сумму с чека', 'attachments.title': 'Прикреплённые файлы', 'attachments.viewAll': 'Посмотреть файлы', 'attachments.file': 'файл', 'attachments.files': 'файла(ов)', 'attachments.saving': 'Сохранение…', 'attachments.error.unsupported': 'Этот тип файла не поддерживается.', 'attachments.error.tooLarge': 'Файл слишком большой. Максимальный размер — 15 МБ.', 'attachments.error.duplicate': 'Этот файл уже добавлен.', 'attachments.error.open': 'Не удалось открыть файл.', 'attachments.error.save': 'Не удалось сохранить файлы. Проверьте хранилище браузера и повторите попытку.',
  'settings.eyebrow': 'Настройки', 'settings.title': 'Настройки приложения', 'settings.appearance': 'Внешний вид', 'settings.appearanceDescription': 'Выберите режим приложения', 'settings.light': '☀️ Светлый режим', 'settings.dark': '🌙 Тёмный режим', 'settings.language': 'Язык', 'settings.languageDescription': 'Выберите язык приложения', 'settings.localData': 'Локальные данные', 'settings.localDataDescription': 'Ваши финансы хранятся в этом браузере и сохраняются после обновления страницы.', 'settings.reset': 'Восстановить демо-данные', 'settings.resetConfirm': 'Все локальные данные будут удалены. Продолжить?',
  'shopping.title': 'Список покупок', 'shopping.eyebrow': 'Общий список семьи', 'shopping.add': '+ Добавить товар', 'shopping.product': 'Название товара', 'shopping.quantity': 'Количество', 'shopping.category': 'Категория', 'shopping.price': 'Ориентировочная цена за единицу', 'shopping.addedBy': 'Добавил', 'shopping.note': 'Заметка', 'shopping.pending': 'Купить', 'shopping.purchased': 'Куплено', 'shopping.markPurchased': 'Отметить купленным', 'shopping.undo': 'Отменить покупку', 'shopping.purchasedBy': 'Купил',
  'transactions.eyebrow': 'Транзакции', 'transactions.title': 'Все операции', 'dashboard.welcome': 'Добро пожаловать 👋', 'dashboard.recent': 'Последние транзакции', 'dashboard.seeAll': 'Все', 'dashboard.budget': 'Месячный бюджет', 'dashboard.quickActions': 'Быстрые действия',
}

const tr: TranslationMap = {
  'nav.home': 'Ana Sayfa', 'nav.transactions': 'İşlemler', 'nav.shopping': 'Alışveriş Listesi', 'nav.budget': 'Bütçe', 'nav.accounts': 'Hesaplar', 'nav.family': 'Aile', 'nav.debts': 'Borçlar ve Taksitler', 'nav.savings': 'Birikimler', 'nav.statistics': 'İstatistikler', 'nav.settings': 'Ayarlar', 'nav.more': 'Daha fazla',
  'common.search': 'Ara', 'common.addIncome': '+ Gelir ekle', 'common.addExpense': '+ Gider ekle', 'common.save': 'Kaydet', 'common.cancel': 'İptal', 'common.edit': 'Düzenle', 'common.delete': 'Sil', 'common.close': 'Kapat', 'common.notifications': 'Bildirimler',
  'header.enableDark': 'Koyu moda geç', 'header.enableLight': 'Açık moda geç', 'header.language': 'Dil seç', 'header.currency': 'Para birimi seç',
  'notifications.title': 'Bildirimler', 'notifications.markAll': 'Tümünü okundu işaretle', 'notifications.empty': 'Finansal bildirim yok', 'notifications.markRead': 'Okundu işaretle', 'notifications.debtDue': '{name} — {amount} ödeme tarihi: {date}', 'notifications.debtOverdue': '{name} — ödeme gecikti ({date})', 'notifications.budgetWarning': '{category}: {limit} tutarının {spent} kadarı kullanıldı', 'notifications.budgetExceeded': '{category}: bütçe limiti aşıldı ({spent} / {limit})', 'notifications.savingsAchieved': '“{name}” birikim hedefine ulaşıldı', 'notifications.reminder': 'Hatırlatma: “{name}” — {date}',
  'transaction.amount': 'Tutar', 'transaction.expenseType': 'Gider türü', 'transaction.personal': 'Kişisel', 'transaction.shared': 'Aile ortak', 'transaction.category': 'Kategori', 'transaction.description': 'Açıklama', 'transaction.incomePlaceholder': 'Örn. maaş, bonus veya diğer', 'transaction.expensePlaceholder': 'Örn. market, yakıt veya diğer', 'transaction.date': 'Tarih', 'transaction.account': 'Hesap', 'transaction.familyMember': 'Aile üyesi', 'transaction.error.amount': 'Geçerli bir tutar girin', 'transaction.error.description': 'Açıklama gerekli', 'transaction.error.people': 'Bir hesap ve aile üyesi seçin',
  'receipt.label': 'Fiş fotoğrafı', 'receipt.optional': 'isteğe bağlı', 'receipt.add': '📷 Fiş fotoğrafı ekle', 'receipt.processing': 'Fotoğraf işleniyor…', 'receipt.replace': 'Fotoğrafı değiştir', 'receipt.remove': 'Fotoğrafı kaldır', 'receipt.view': 'Fişi görüntüle', 'receipt.attached': '📎 Fiş', 'receipt.previewAlt': 'Fiş fotoğrafı önizlemesi', 'receipt.help': 'Fotoğraf sıkıştırılarak bu cihazda güvenle saklanır.', 'receipt.error.notImage': 'Lütfen bir görsel dosyası seçin.', 'receipt.error.tooLarge': 'Bu fotoğraf çok büyük. 12 MB altında bir dosya seçin.', 'receipt.error.processingFailed': 'Fotoğraf işlenemedi. JPG veya PNG dosyası deneyin.',
  'receipt.ocrProcessing': 'Fiş işleniyor…', 'receipt.ocrDetected': 'Tutar otomatik algılandı', 'receipt.ocrUncertain': 'Tutarı kesin olarak algılayamadık — lütfen kontrol edin', 'receipt.detectedBadge': '✓ Fişten algılandı', 'receipt.viewerControls': 'Fiş görüntüsü kontrolleri', 'receipt.zoomIn': 'Yakınlaştır', 'receipt.zoomOut': 'Uzaklaştır', 'receipt.resetZoom': 'Yakınlaştırmayı sıfırla', 'receipt.rotateLeft': 'Sola döndür', 'receipt.rotateRight': 'Sağa döndür',
  'receipt.ocrReading': 'Fişteki tutar okunuyor…', 'receipt.ocrFailed': 'Fişteki tutar algılanamadı — elle girin', 'receipt.reprocess': 'Tutarı tekrar oku',
  'attachments.label': 'Dosyalar ve belgeler', 'attachments.add': '+ Dosya ekle', 'attachments.help': 'Fotoğraf, PDF, Excel veya Word belgesi ekleyebilirsiniz', 'attachments.view': 'Görüntüle', 'attachments.viewPdf': 'PDF’yi görüntüle', 'attachments.open': 'Aç/indir', 'attachments.replace': 'Değiştir', 'attachments.remove': 'Kaldır', 'attachments.readAmount': 'Fişteki tutarı oku', 'attachments.title': 'Ekli dosyalar', 'attachments.viewAll': 'Dosyaları görüntüle', 'attachments.file': 'dosya', 'attachments.files': 'dosya', 'attachments.saving': 'Kaydediliyor…', 'attachments.error.unsupported': 'Bu dosya türü desteklenmiyor.', 'attachments.error.tooLarge': 'Dosya çok büyük. En fazla 15 MB olabilir.', 'attachments.error.duplicate': 'Bu dosya zaten eklendi.', 'attachments.error.open': 'Dosya açılamadı.', 'attachments.error.save': 'Dosyalar kaydedilemedi. Tarayıcı depolamasını kontrol edip tekrar deneyin.',
  'settings.eyebrow': 'Ayarlar', 'settings.title': 'Uygulama ayarları', 'settings.appearance': 'Görünüm', 'settings.appearanceDescription': 'Uygulama modunuzu seçin', 'settings.light': '☀️ Açık mod', 'settings.dark': '🌙 Koyu mod', 'settings.language': 'Dil', 'settings.languageDescription': 'Uygulama dilinizi seçin', 'settings.localData': 'Yerel veriler', 'settings.localDataDescription': 'Finans bilgileriniz bu tarayıcıda saklanır ve sayfa yenilendikten sonra korunur.', 'settings.reset': 'Demo verilerini sıfırla', 'settings.resetConfirm': 'Tüm yerel veriler silinecek. Devam edilsin mi?',
  'shopping.title': 'Alışveriş Listesi', 'shopping.eyebrow': 'Ortak aile listesi', 'shopping.add': '+ Ürün ekle', 'shopping.product': 'Ürün adı', 'shopping.quantity': 'Miktar', 'shopping.category': 'Kategori', 'shopping.price': 'Tahmini birim fiyatı', 'shopping.addedBy': 'Ekleyen', 'shopping.note': 'Not', 'shopping.pending': 'Alınacak', 'shopping.purchased': 'Alındı', 'shopping.markPurchased': 'Alındı olarak işaretle', 'shopping.undo': 'Alımı geri al', 'shopping.purchasedBy': 'Alan',
  'transactions.eyebrow': 'İşlemler', 'transactions.title': 'Tüm hareketler', 'dashboard.welcome': 'Hoş geldiniz 👋', 'dashboard.recent': 'Son işlemler', 'dashboard.seeAll': 'Tümünü gör', 'dashboard.budget': 'Aylık bütçe', 'dashboard.quickActions': 'Hızlı işlemler',
}

export const translations: Record<Language, TranslationMap> = { ka, en, ru, tr }
export function translate(language: Language, key: string) { return translations[language][key] ?? translations.ka[key] ?? key }
