import { useState, type FormEvent, type ReactNode } from 'react'
import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { HeaderPreferences } from '../components/HeaderPreferences'
import { useFinance } from '../state/FinanceContext'
import { useAuth } from '../state/AuthContext'
import { AuthConfigurationError } from '../services/authService'

const text = {
  ka: { login:'შესვლა', loginTitle:'კეთილი იყოს თქვენი დაბრუნება', loginHelp:'შედით თქვენი ოჯახის ფინანსების სამართავად.', email:'ელფოსტა', password:'პაროლი', remember:'დამახსოვრება', forgot:'დაგავიწყდათ პაროლი?', create:'ანგარიშის შექმნა', noAccount:'ჯერ არ გაქვთ ანგარიში?', register:'რეგისტრაცია', registerTitle:'შექმენით ანგარიში', registerHelp:'შეავსეთ მონაცემები უსაფრთხო ანგარიშის შესაქმნელად.', fullName:'სახელი და გვარი', confirm:'გაიმეორეთ პაროლი', haveAccount:'უკვე გაქვთ ანგარიში?', back:'შესვლაზე დაბრუნება', forgotTitle:'პაროლის აღდგენა', forgotHelp:'შეიყვანეთ ელფოსტა აღდგენის ინსტრუქციის მისაღებად.', send:'ინსტრუქციის გაგზავნა', mismatch:'პაროლები არ ემთხვევა.', required:'შეავსეთ ყველა სავალდებულო ველი.', configured:'ავტორიზაციის სერვისი ჯერ არ არის დაკავშირებული. ანგარიშები არ შეიქმნება და პაროლები ბრაუზერში არ შეინახება.', sent:'თუ ანგარიში არსებობს, აღდგენის ინსტრუქცია გაიგზავნა.', registered:'ანგარიში შეიქმნა. ახლა შეგიძლიათ შესვლა.' },
  en: { login:'Sign in', loginTitle:'Welcome back', loginHelp:'Sign in to manage your family finances.', email:'Email', password:'Password', remember:'Remember me', forgot:'Forgot password?', create:'Create account', noAccount:"Don't have an account?", register:'Register', registerTitle:'Create your account', registerHelp:'Enter your details to create a secure account.', fullName:'Full name', confirm:'Confirm password', haveAccount:'Already have an account?', back:'Back to sign in', forgotTitle:'Reset your password', forgotHelp:'Enter your email to receive recovery instructions.', send:'Send instructions', mismatch:'Passwords do not match.', required:'Complete all required fields.', configured:'Authentication service is not configured yet. No account will be created and no password will be stored in this browser.', sent:'If the account exists, recovery instructions were sent.', registered:'Account created. You can now sign in.' },
  ru: { login:'Войти', loginTitle:'С возвращением', loginHelp:'Войдите, чтобы управлять семейными финансами.', email:'Эл. почта', password:'Пароль', remember:'Запомнить меня', forgot:'Забыли пароль?', create:'Создать аккаунт', noAccount:'Нет аккаунта?', register:'Регистрация', registerTitle:'Создайте аккаунт', registerHelp:'Заполните данные для создания защищённого аккаунта.', fullName:'Имя и фамилия', confirm:'Повторите пароль', haveAccount:'Уже есть аккаунт?', back:'Вернуться ко входу', forgotTitle:'Восстановление пароля', forgotHelp:'Введите почту для получения инструкций.', send:'Отправить инструкции', mismatch:'Пароли не совпадают.', required:'Заполните все обязательные поля.', configured:'Сервис авторизации пока не подключён. Аккаунты не создаются, пароли не сохраняются в браузере.', sent:'Если аккаунт существует, инструкции отправлены.', registered:'Аккаунт создан. Теперь можно войти.' },
  tr: { login:'Giriş yap', loginTitle:'Tekrar hoş geldiniz', loginHelp:'Aile finansınızı yönetmek için giriş yapın.', email:'E-posta', password:'Şifre', remember:'Beni hatırla', forgot:'Şifrenizi mi unuttunuz?', create:'Hesap oluştur', noAccount:'Hesabınız yok mu?', register:'Kayıt ol', registerTitle:'Hesabınızı oluşturun', registerHelp:'Güvenli bir hesap oluşturmak için bilgilerinizi girin.', fullName:'Ad soyad', confirm:'Şifreyi doğrula', haveAccount:'Zaten hesabınız var mı?', back:'Girişe dön', forgotTitle:'Şifrenizi sıfırlayın', forgotHelp:'Kurtarma talimatları için e-postanızı girin.', send:'Talimatları gönder', mismatch:'Şifreler eşleşmiyor.', required:'Tüm zorunlu alanları doldurun.', configured:'Kimlik doğrulama hizmeti henüz yapılandırılmadı. Hesap oluşturulmaz ve şifre tarayıcıda saklanmaz.', sent:'Hesap varsa kurtarma talimatları gönderildi.', registered:'Hesap oluşturuldu. Şimdi giriş yapabilirsiniz.' },
} as const

const inputClass = 'w-full rounded-2xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white'

function AuthLayout({ title, help, children }: { title: string; help: string; children: ReactNode }) {
  const { preferences } = useFinance()
  return <div className={`theme-${preferences.theme} min-h-screen bg-slate-100 px-4 py-6 text-slate-900 sm:px-6`}>
    <div className="mx-auto flex max-w-6xl justify-end"><HeaderPreferences showCurrency={false} /></div>
    <div className="mx-auto flex min-h-[calc(100vh-6rem)] max-w-6xl items-center justify-center py-8">
      <div className="w-full max-w-md rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl sm:p-8">
        <div className="mb-7 flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-600 text-white"><LockKeyhole className="h-6 w-6" /></div>
        <h1 className="text-3xl font-bold text-slate-900">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{help}</p>
        {children}
      </div>
    </div>
  </div>
}

function PasswordField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  const [visible, setVisible] = useState(false)
  return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}</span><span className="relative block"><LockKeyhole className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type={visible ? 'text' : 'password'} value={value} onChange={(event) => onChange(event.target.value)} className={`${inputClass} pr-11`} autoComplete="current-password" required /><button type="button" onClick={() => setVisible((current) => !current)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" aria-label="Show password">{visible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></span></label>
}

function ErrorMessage({ value }: { value: string }) { return value ? <p className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700" role="alert">{value}</p> : null }

export function LoginPage() {
  const { preferences } = useFinance(); const c = text[preferences.language]; const auth = useAuth(); const navigate = useNavigate()
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [remember,setRemember]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!email.trim() || !password) return setError(c.required); setBusy(true); setError(''); try { await auth.login(email.trim(),password,remember); navigate('/',{replace:true}) } catch (reason) { setError(reason instanceof AuthConfigurationError ? c.configured : reason instanceof Error ? reason.message : c.required) } finally { setBusy(false) } }
  return <AuthLayout title={c.loginTitle} help={c.loginHelp}><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.email}</span><span className="relative block"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className={inputClass} autoComplete="email" required /></span></label><PasswordField label={c.password} value={password} onChange={setPassword} /><div className="flex items-center justify-between gap-3 text-sm"><label className="flex items-center gap-2 text-slate-600"><input type="checkbox" checked={remember} onChange={(e)=>setRemember(e.target.checked)} className="h-4 w-4 accent-emerald-600" />{c.remember}</label><Link to="/forgot-password" className="font-medium text-emerald-700">{c.forgot}</Link></div><ErrorMessage value={error} /><button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{c.login}</button></form><p className="mt-6 text-center text-sm text-slate-500">{c.noAccount} <Link to="/register" className="font-semibold text-emerald-700">{c.create}</Link></p></AuthLayout>
}

export function RegisterPage() {
  const { preferences }=useFinance(); const c=text[preferences.language]; const auth=useAuth(); const navigate=useNavigate(); const [form,setForm]=useState({fullName:'',email:'',password:'',confirm:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.fullName.trim()||!form.email.trim()||!form.password||!form.confirm)return setError(c.required);if(form.password!==form.confirm)return setError(c.mismatch);setBusy(true);setError('');try{await auth.register(form.fullName,form.email.trim(),form.password);navigate('/login',{replace:true,state:{message:c.registered}})}catch(reason){setError(reason instanceof AuthConfigurationError?c.configured:reason instanceof Error?reason.message:c.required)}finally{setBusy(false)}}
  return <AuthLayout title={c.registerTitle} help={c.registerHelp}><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.fullName}</span><span className="relative block"><UserRound className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})} className={inputClass} autoComplete="name" /></span></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.email}</span><span className="relative block"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className={inputClass} autoComplete="email" /></span></label><PasswordField label={c.password} value={form.password} onChange={(value)=>setForm({...form,password:value})} /><PasswordField label={c.confirm} value={form.confirm} onChange={(value)=>setForm({...form,confirm:value})} /><ErrorMessage value={error} /><button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{c.register}</button></form><p className="mt-6 text-center text-sm text-slate-500">{c.haveAccount} <Link to="/login" className="font-semibold text-emerald-700">{c.login}</Link></p></AuthLayout>
}

export function ForgotPasswordPage() {
  const {preferences}=useFinance();const c=text[preferences.language];const auth=useAuth();const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('')
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!email.trim())return setError(c.required);setError('');setMessage('');try{await auth.forgotPassword(email.trim());setMessage(c.sent)}catch(reason){setError(reason instanceof AuthConfigurationError?c.configured:reason instanceof Error?reason.message:c.required)}}
  return <AuthLayout title={c.forgotTitle} help={c.forgotHelp}><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.email}</span><span className="relative block"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className={inputClass} autoComplete="email" /></span></label><ErrorMessage value={error} />{message?<p className="rounded-xl bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{message}</p>:null}<button className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white">{c.send}</button></form><Link to="/login" className="mt-6 flex items-center justify-center gap-2 text-sm font-semibold text-emerald-700"><ArrowLeft className="h-4 w-4" />{c.back}</Link></AuthLayout>
}
