import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { HeaderPreferences } from '../components/HeaderPreferences'
import { useFinance } from '../state/FinanceContext'
import { useAuth } from '../state/AuthContext'
import { AuthConfigurationError } from '../services/authService'

const text = {
  ka: { login:'შესვლა', loginTitle:'კეთილი იყოს თქვენი დაბრუნება', loginHelp:'შედით თქვენი ოჯახის ფინანსების სამართავად.', email:'ელფოსტა', password:'პაროლი', remember:'დამახსოვრება', forgot:'დაგავიწყდათ პაროლი?', create:'ანგარიშის შექმნა', noAccount:'ჯერ არ გაქვთ ანგარიში?', register:'რეგისტრაცია', registerTitle:'შექმენით ანგარიში', registerHelp:'შეავსეთ მონაცემები უსაფრთხო ანგარიშის შესაქმნელად.', fullName:'სახელი და გვარი', confirm:'გაიმეორეთ პაროლი', haveAccount:'უკვე გაქვთ ანგარიში?', back:'შესვლაზე დაბრუნება', forgotTitle:'პაროლის აღდგენა', forgotHelp:'შეიყვანეთ ელფოსტა აღდგენის ინსტრუქციის მისაღებად.', send:'ინსტრუქციის გაგზავნა', mismatch:'პაროლები არ ემთხვევა.', required:'შეავსეთ ყველა სავალდებულო ველი.', configured:'ავტორიზაციის სერვისი ჯერ არ არის დაკავშირებული. ანგარიშები არ შეიქმნება და პაროლები ბრაუზერში არ შეინახება.', sent:'თუ ანგარიში არსებობს, აღდგენის ინსტრუქცია გაიგზავნა.', checkTitle:'შეამოწმეთ ელფოსტა', checkHelp:'ანგარიშის დასადასტურებლად გამოგზავნილ წერილში დააჭირეთ ბმულს. დადასტურების შემდეგ ავტომატურად გადახვალთ მთავარ გვერდზე.', resend:'წერილის ხელახლა გაგზავნა', resent:'დადასტურების წერილი ხელახლა გაიგზავნა.', resetTitle:'შექმენით ახალი პაროლი', resetHelp:'ახალი პაროლი მინიმუმ 6 სიმბოლოს უნდა შეიცავდეს.', update:'პაროლის განახლება', updated:'პაროლი წარმატებით განახლდა.', invalidLink:'აღდგენის ბმული არასწორია ან ვადაგასულია. მოითხოვეთ ახალი ბმული.', minPassword:'პაროლი მინიმუმ 6 სიმბოლოს უნდა შეიცავდეს.', loading:'მიმდინარეობს ავტორიზაციის შემოწმება…' },
  en: { login:'Sign in', loginTitle:'Welcome back', loginHelp:'Sign in to manage your family finances.', email:'Email', password:'Password', remember:'Remember me', forgot:'Forgot password?', create:'Create account', noAccount:"Don't have an account?", register:'Register', registerTitle:'Create your account', registerHelp:'Enter your details to create a secure account.', fullName:'Full name', confirm:'Confirm password', haveAccount:'Already have an account?', back:'Back to sign in', forgotTitle:'Reset your password', forgotHelp:'Enter your email to receive recovery instructions.', send:'Send instructions', mismatch:'Passwords do not match.', required:'Complete all required fields.', configured:'Authentication service is not configured yet. No account will be created and no password will be stored in this browser.', sent:'If the account exists, recovery instructions were sent.', checkTitle:'Check your email', checkHelp:'Open the confirmation email and follow its link. You will be sent to the dashboard after confirmation.', resend:'Resend confirmation', resent:'The confirmation email was sent again.', resetTitle:'Choose a new password', resetHelp:'Your new password must contain at least 6 characters.', update:'Update password', updated:'Your password was updated.', invalidLink:'This recovery link is invalid or expired. Request a new link.', minPassword:'The password must contain at least 6 characters.', loading:'Restoring your session…' },
  ru: { login:'Войти', loginTitle:'С возвращением', loginHelp:'Войдите, чтобы управлять семейными финансами.', email:'Эл. почта', password:'Пароль', remember:'Запомнить меня', forgot:'Забыли пароль?', create:'Создать аккаунт', noAccount:'Нет аккаунта?', register:'Регистрация', registerTitle:'Создайте аккаунт', registerHelp:'Заполните данные для создания защищённого аккаунта.', fullName:'Имя и фамилия', confirm:'Повторите пароль', haveAccount:'Уже есть аккаунт?', back:'Вернуться ко входу', forgotTitle:'Восстановление пароля', forgotHelp:'Введите почту для получения инструкций.', send:'Отправить инструкции', mismatch:'Пароли не совпадают.', required:'Заполните все обязательные поля.', configured:'Сервис авторизации пока не подключён. Аккаунты не создаются, пароли не сохраняются в браузере.', sent:'Если аккаунт существует, инструкции отправлены.', checkTitle:'Проверьте почту', checkHelp:'Откройте письмо и перейдите по ссылке подтверждения. После подтверждения вы попадёте на главную страницу.', resend:'Отправить ещё раз', resent:'Письмо подтверждения отправлено повторно.', resetTitle:'Новый пароль', resetHelp:'Новый пароль должен содержать не менее 6 символов.', update:'Обновить пароль', updated:'Пароль успешно обновлён.', invalidLink:'Ссылка недействительна или устарела. Запросите новую ссылку.', minPassword:'Пароль должен содержать не менее 6 символов.', loading:'Восстанавливаем сеанс…' },
  tr: { login:'Giriş yap', loginTitle:'Tekrar hoş geldiniz', loginHelp:'Aile finansınızı yönetmek için giriş yapın.', email:'E-posta', password:'Şifre', remember:'Beni hatırla', forgot:'Şifrenizi mi unuttunuz?', create:'Hesap oluştur', noAccount:'Hesabınız yok mu?', register:'Kayıt ol', registerTitle:'Hesabınızı oluşturun', registerHelp:'Güvenli bir hesap oluşturmak için bilgilerinizi girin.', fullName:'Ad soyad', confirm:'Şifreyi doğrula', haveAccount:'Zaten hesabınız var mı?', back:'Girişe dön', forgotTitle:'Şifrenizi sıfırlayın', forgotHelp:'Kurtarma talimatları için e-postanızı girin.', send:'Talimatları gönder', mismatch:'Şifreler eşleşmiyor.', required:'Tüm zorunlu alanları doldurun.', configured:'Kimlik doğrulama hizmeti henüz yapılandırılmadı. Hesap oluşturulmaz ve şifre tarayıcıda saklanmaz.', sent:'Hesap varsa kurtarma talimatları gönderildi.', checkTitle:'E-postanızı kontrol edin', checkHelp:'Onay e-postasındaki bağlantıyı açın. Onaydan sonra ana sayfaya yönlendirileceksiniz.', resend:'Onayı yeniden gönder', resent:'Onay e-postası yeniden gönderildi.', resetTitle:'Yeni şifre belirleyin', resetHelp:'Yeni şifre en az 6 karakter olmalıdır.', update:'Şifreyi güncelle', updated:'Şifreniz güncellendi.', invalidLink:'Bağlantı geçersiz veya süresi dolmuş. Yeni bağlantı isteyin.', minPassword:'Şifre en az 6 karakter olmalıdır.', loading:'Oturumunuz geri yükleniyor…' },
} as const

const inputClass = 'w-full rounded-2xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white'
const pendingConfirmationEmailKey = 'finance-pending-confirmation-email'

function AuthLayout({ title, help, children }: { title: string; help: string; children: ReactNode }) {
  const { preferences } = useFinance()
  return <div className={`theme-${preferences.theme} min-h-screen bg-slate-100 px-4 py-6 text-slate-900 sm:px-6`}>
    <div className="mx-auto flex max-w-6xl justify-end"><HeaderPreferences /></div>
    <div className="mx-auto flex min-h-[calc(100vh-6rem)] max-w-6xl items-center justify-center py-8">
      <div className="w-full max-w-md rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl sm:p-8">
        <div className="mb-7 flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-600 text-white"><LockKeyhole className="h-6 w-6" /></div>
        <h1 className="text-3xl font-bold text-slate-900">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{help}</p>
        {children}
      </div>
    </div>
  </div>
}

function PasswordField({ label, value, onChange, autoComplete = 'current-password' }: { label: string; value: string; onChange: (value: string) => void; autoComplete?: string }) {
  const [visible, setVisible] = useState(false)
  return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}</span><span className="relative block"><LockKeyhole className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type={visible ? 'text' : 'password'} value={value} onChange={(event) => onChange(event.target.value)} className={`${inputClass} pr-11`} autoComplete={autoComplete} required /><button type="button" onClick={() => setVisible((current) => !current)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" aria-label="Show password">{visible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></span></label>
}

function ErrorMessage({ value }: { value: string }) { return value ? <p className="rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700" role="alert">{value}</p> : null }
function SuccessMessage({ value }: { value: string }) { return value ? <p className="rounded-xl bg-emerald-50 px-3 py-2 text-sm text-emerald-700" role="status">{value}</p> : null }

export function LoginPage() {
  const { preferences } = useFinance(); const c = text[preferences.language]; const auth = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [remember,setRemember]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const message = typeof location.state === 'object' && location.state !== null && 'message' in location.state ? String(location.state.message) : ''
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!email.trim() || !password) return setError(c.required); setBusy(true); setError(''); try { await auth.login(email.trim(),password,remember); sessionStorage.removeItem(pendingConfirmationEmailKey); navigate('/',{replace:true}) } catch (reason) { setError(reason instanceof AuthConfigurationError ? c.configured : reason instanceof Error ? reason.message : c.required) } finally { setBusy(false) } }
  return <AuthLayout title={c.loginTitle} help={c.loginHelp}><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.email}</span><span className="relative block"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className={inputClass} autoComplete="email" required /></span></label><PasswordField label={c.password} value={password} onChange={setPassword} /><div className="flex items-center justify-between gap-3 text-sm"><label className="flex items-center gap-2 text-slate-600"><input type="checkbox" checked={remember} onChange={(e)=>setRemember(e.target.checked)} className="h-4 w-4 accent-emerald-600" />{c.remember}</label><Link to="/forgot-password" className="font-medium text-emerald-700">{c.forgot}</Link></div><SuccessMessage value={message} /><ErrorMessage value={error} /><button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{c.login}</button></form><p className="mt-6 text-center text-sm text-slate-500">{c.noAccount} <Link to="/register" className="font-semibold text-emerald-700">{c.create}</Link></p></AuthLayout>
}

export function RegisterPage() {
  const { preferences }=useFinance(); const c=text[preferences.language]; const auth=useAuth(); const navigate=useNavigate(); const [form,setForm]=useState({fullName:'',email:'',password:'',confirm:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.fullName.trim()||!form.email.trim()||!form.password||!form.confirm)return setError(c.required);if(form.password!==form.confirm)return setError(c.mismatch);if(form.password.length<6)return setError(c.minPassword);setBusy(true);setError('');try{const normalizedEmail=form.email.trim();const result=await auth.register(form.fullName,normalizedEmail,form.password);if(result.requiresEmailConfirmation){sessionStorage.setItem(pendingConfirmationEmailKey,normalizedEmail);navigate('/check-email',{replace:true,state:{email:normalizedEmail}})}else navigate('/',{replace:true})}catch(reason){setError(reason instanceof AuthConfigurationError?c.configured:reason instanceof Error?reason.message:c.required)}finally{setBusy(false)}}
  return <AuthLayout title={c.registerTitle} help={c.registerHelp}><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.fullName}</span><span className="relative block"><UserRound className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})} className={inputClass} autoComplete="name" /></span></label><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.email}</span><span className="relative block"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className={inputClass} autoComplete="email" /></span></label><PasswordField label={c.password} value={form.password} onChange={(value)=>setForm({...form,password:value})} autoComplete="new-password" /><PasswordField label={c.confirm} value={form.confirm} onChange={(value)=>setForm({...form,confirm:value})} autoComplete="new-password" /><ErrorMessage value={error} /><button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{c.register}</button></form><p className="mt-6 text-center text-sm text-slate-500">{c.haveAccount} <Link to="/login" className="font-semibold text-emerald-700">{c.login}</Link></p></AuthLayout>
}

export function CheckEmailPage() {
  const {preferences}=useFinance(); const c=text[preferences.language]; const auth=useAuth(); const location=useLocation(); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
  const email = typeof location.state === 'object' && location.state !== null && 'email' in location.state ? String(location.state.email) : sessionStorage.getItem(pendingConfirmationEmailKey) ?? ''
  const resend=async()=>{if(!email)return setError(c.required);setBusy(true);setError('');setMessage('');try{await auth.resendConfirmation(email);setMessage(c.resent)}catch(reason){setError(reason instanceof Error?reason.message:c.required)}finally{setBusy(false)}}
  return <AuthLayout title={c.checkTitle} help={c.checkHelp}><div className="mt-7 space-y-4">{email?<p className="rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-700">{email}</p>:null}<SuccessMessage value={message} /><ErrorMessage value={error} /><button type="button" disabled={busy||!email} onClick={()=>void resend()} className="w-full rounded-xl border border-emerald-200 px-4 py-3 font-semibold text-emerald-700 disabled:opacity-60">{c.resend}</button><Link to="/login" className="flex items-center justify-center gap-2 text-sm font-semibold text-emerald-700"><ArrowLeft className="h-4 w-4" />{c.back}</Link></div></AuthLayout>
}

export function ForgotPasswordPage() {
  const {preferences}=useFinance();const c=text[preferences.language];const auth=useAuth();const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!email.trim())return setError(c.required);setBusy(true);setError('');setMessage('');try{await auth.forgotPassword(email.trim());setMessage(c.sent)}catch(reason){setError(reason instanceof AuthConfigurationError?c.configured:reason instanceof Error?reason.message:c.required)}finally{setBusy(false)}}
  return <AuthLayout title={c.forgotTitle} help={c.forgotHelp}><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{c.email}</span><span className="relative block"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className={inputClass} autoComplete="email" /></span></label><ErrorMessage value={error} /><SuccessMessage value={message} /><button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{c.send}</button></form><Link to="/login" className="mt-6 flex items-center justify-center gap-2 text-sm font-semibold text-emerald-700"><ArrowLeft className="h-4 w-4" />{c.back}</Link></AuthLayout>
}

export function ResetPasswordPage() {
  const {preferences}=useFinance(); const c=text[preferences.language]; const auth=useAuth(); const navigate=useNavigate(); const [form,setForm]=useState({password:'',confirm:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();if(form.password!==form.confirm)return setError(c.mismatch);if(form.password.length<6)return setError(c.minPassword);setBusy(true);setError('');try{await auth.updatePassword(form.password);navigate('/',{replace:true})}catch(reason){setError(reason instanceof Error?reason.message:c.required)}finally{setBusy(false)}}
  if(auth.checking)return <AuthLayout title={c.resetTitle} help={c.loading}><div className="mt-7 h-1 animate-pulse rounded bg-emerald-500" /></AuthLayout>
  if(!auth.user)return <AuthLayout title={c.resetTitle} help={c.invalidLink}><Link to="/forgot-password" className="mt-7 flex items-center justify-center gap-2 text-sm font-semibold text-emerald-700"><ArrowLeft className="h-4 w-4" />{c.forgot}</Link></AuthLayout>
  return <AuthLayout title={c.resetTitle} help={c.resetHelp}><form onSubmit={submit} className="mt-7 space-y-4"><PasswordField label={c.password} value={form.password} onChange={(value)=>setForm({...form,password:value})} autoComplete="new-password" /><PasswordField label={c.confirm} value={form.confirm} onChange={(value)=>setForm({...form,confirm:value})} autoComplete="new-password" /><ErrorMessage value={error} /><button disabled={busy} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{c.update}</button></form></AuthLayout>
}

export function AuthCallbackPage() {
  const {preferences}=useFinance(); const c=text[preferences.language]; const auth=useAuth(); const location=useLocation(); const navigate=useNavigate()
  const hasError = new URLSearchParams(location.search).has('error') || new URLSearchParams(location.hash.replace(/^#/, '')).has('error')
  useEffect(()=>{if(!auth.checking&&auth.user){sessionStorage.removeItem(pendingConfirmationEmailKey);navigate('/',{replace:true})}},[auth.checking,auth.user,navigate])
  if(hasError)return <AuthLayout title={c.checkTitle} help={c.invalidLink}><Link to="/login" className="mt-7 flex items-center justify-center gap-2 text-sm font-semibold text-emerald-700"><ArrowLeft className="h-4 w-4" />{c.back}</Link></AuthLayout>
  if(!auth.checking&&!auth.user)return <Navigate to="/login" replace />
  return <AuthLayout title={c.checkTitle} help={c.loading}><div className="mt-7 h-1 animate-pulse rounded bg-emerald-500" /></AuthLayout>
}
