import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useFinance } from '../state/FinanceContext'
import { calculateIncome, calculateExpenses, calculateSavings, monthKey } from '../utils/calculations'
import { formatCurrency } from '../utils/formatters'
import { localeMap } from '../i18n/translations'

export function StatisticsPage() {
  const { validTransactions: transactions, savingsGoals, preferences } = useFinance()
  const money = (value: number) => formatCurrency(value, preferences.currency, localeMap[preferences.language])
  const months = Array.from(new Set(transactions.map((item) => monthKey(item.date)))).sort()
  const monthlyStats = months.map((month) => ({ month, income: calculateIncome(transactions, month), expense: calculateExpenses(transactions, month), savings: calculateSavings(savingsGoals) }))
  const categories = Array.from(new Set(transactions.map((item) => item.category))).map((name) => ({ name, value: transactions.filter((item) => item.type === 'expense' && item.category === name).reduce((sum, item) => sum + item.amount, 0) }))
  return <div className="space-y-6"><div><p className="text-sm uppercase tracking-[0.2em] text-slate-500">სტატისტიკა</p><h1 className="mt-2 text-3xl font-bold text-slate-900">ფინანსური ცვლილებები</h1></div><div className="grid gap-6 xl:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-semibold text-slate-900">შემოსავალი და ხარჯი</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyStats}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="month" stroke="#64748b" /><YAxis stroke="#64748b" tickFormatter={(value) => money(Number(value))} /><Tooltip formatter={(value) => money(Number(value ?? 0))} /><Line type="monotone" dataKey="income" stroke="#10b981" strokeWidth={3} /><Line type="monotone" dataKey="expense" stroke="#f97316" strokeWidth={3} /></LineChart></ResponsiveContainer></div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-semibold text-slate-900">დანაზოგი</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyStats}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="month" stroke="#64748b" /><YAxis stroke="#64748b" tickFormatter={(value) => money(Number(value))} /><Tooltip formatter={(value) => money(Number(value ?? 0))} /><Bar dataKey="savings" fill="#38bdf8" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-semibold text-slate-900">ხარჯები კატეგორიების მიხედვით</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={categories}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="name" stroke="#64748b" /><YAxis stroke="#64748b" tickFormatter={(value) => money(Number(value))} /><Tooltip formatter={(value) => money(Number(value ?? 0))} /><Bar dataKey="value" fill="#10b981" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></div></div>
}
